name: End-to-end Tests

on:
  # Uncomment the next three lines to run on a schedule
  # schedule:
  #  # Runs our tests at the top of every hour
  #  - cron:  '0 * * * *'
  workflow_dispatch:
    inputs:
      e2eScript:
        description: End-to-end test scripts for AWS Connect
        required: true
        default: 'v2'
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install 
      
      - name: Test
        run: npm test
      
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test_output
          path: test_output
