name: End-to-end Tests

on:
  # Uncomment the next three lines to run on a schedule
  # schedule:
  #  # Runs our tests at the top of every hour
  #  - cron:  '0 * * * *'
  workflow_dispatch:
    inputs:
      e2eScript:
        description: End-to-end test scripts for AWS Connect
        required: true
        default: 'v2'

env:
  # Replace this with your own DataDog API key for real testing
  # Directions here: https://gitlab.com/bespoken/bespoken-datadog-plugin#bespoken-datadog-plugin
  DATADOG_API_KEY: 86f0c743a4f6990f7778b78333e84a9e
  DATADOG_CUSTOMER: "Bespoken Airlines Connect"
  PHONE_NUMBER: 17162475149
  # Replace this with your own virtual device for real testing
  # Directions here: https://read.bespoken.io/end-to-end/getting-started/#overview
  VIRTUAL_DEVICE_TOKEN: phone-e5787cd7-8fef-4d3a-9847-d2cc2d65f815
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install 
      
      - name: Test
        run: npm test
      
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test_output
          path: test_output
